INSERT INTO barang (barang_deskripsi)
VALUES
    ('POLLARD'),
    ('SOYABEANSEED'),
    ('SUGAR'),
    ('LAIN-LAIN'),
    ('SBM'),
    ('PELLET'),
    ('GANDUM'),
    ('KEDELE'),
    ('JAGUNG'),
    ('KEDELE'),
    ('RAPE SEED'),
    ('B.KETAN'),
    ('ASBM'),
    ('WHEAT'),
    ('CORN'),
    ('YELLOW'),
    ('IRSM'),
    ('B.SAWIT'),
    ('MBM'),
    ('B.KOPRA'),
    ('C.FEATHER'),
    ('KATUL'),
    ('RICE BRAN'),
    ('STONE CHIPS'),
    ('MCP'),
    ('GAPLEX'),
    ('CANGKANG'),
    ('CGM'),
    ('TAPIOCA'),
    ('PKM'),
    ('DCP'),
    ('DDGS'),
    ('FISH'),
    ('FULFAT'),
    ('CRUMBLE'),
    ('BERAS'),
    ('CARGO'),
    ('PKE'),
    ('WOOD'),
    ('BULOG'),
    ('WOOD CHIP'),
    ('SODIUM'),
    ('RSM');